### ISSUE TITLE
微调完成，但是在模型合并中报错，非常感谢

### ISSUE THREAD

**Issue by ufo5** [echonoshy/cgft-llm#6]
It looks like the config file at 'model.safetensors' is not a valid JSON file.

**Comment by ufo5** [comment]
model_name_or_path: model.safetensors
adapter_name_or_path: saves\\Qwen1.5-0.5B\\lora\\train_2024-07-12-21-09-48
template: Qwen1.5-0.5B
finetuning_type: lora


### export
export_dir: PycharmProjects\\pythonProject\\Qwen1.5-0.5B-Chat-merged
export_size: 4
export_device: cuda
export_legacy_format:   false

**Comment by echonoshy** [comment]
Did you download the model files from the official huggingface or modelscope?

**Comment by ufo5** [comment]
yes ,i have ,
![001-合并](https://github.com/user-attachments/assets/e491ddc5-6cfa-4694-920b-19881eff6d62)

**Comment by ufo5** [comment]
susseccful，the problem is the template name wrong.thanks

**Comment by echonoshy** [comment]
glad you solve it.
