### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by HAOYON-666** [echonoshy/cgft-llm#9]
(myenv) (base) root@master-22:/data/zhy/tools/llama.cpp# cmake -B build_cuda -DLLAMA_CUDA=ON
-- The C compiler identification is GNU 12.3.0
-- The CXX compiler identification is GNU 12.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.34.1") 
CMake Warning at CMakeLists.txt:95 (message):
  LLAMA_CUDA is deprecated and will be removed in the future.

  Use GGML_CUDA instead

Call Stack (most recent call first):
  CMakeLists.txt:101 (llama_option_depr)

please tell me how to deal with,thanks!
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- OpenMP found
-- Using llamafile
-- Could not find nvcc, please set CUDAToolkit_ROOT.
CMake Warning at ggml/src/CMakeLists.txt:400 (message):
  CUDA not found

-- CUDA host compiler is GNU 
CMake Error at ggml/src/CMakeLists.txt:1010 (get_flags):
  get_flags Function invoked with incorrect arguments for function named:
  get_flags

-- Warning: ccache not found - consider installing it for faster compilation or disable this warning with GGML_CCACHE=OFF
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- x86 detected
-- Configuring incomplete, errors occurred!
See also "/data/zhy/tools/llama.cpp/build_cuda/CMakeFiles/CMakeOutput.log".

**Comment by HAOYON-666** [comment]
please tell me how to deal with,thanks!

**Comment by echonoshy** [comment]
Hi, llama.cpp released a lot of new feathers recently, so some apis are deprecated…
You can use following instead:

cmake -B build -DGGML_CUDA=ON
cmake --build build --config Release

Btw, I will update a new patch video for that.sorry for your inconvenience.
